version: '3.8'

services:
  my_dotnet_app:
    image: my_dotnet
    build:
      context: .
      dockerfile: ${{ secrets.DOCKER_USERNAME }}/my-app
    ports:
      - "5010:80"
    environment:
      - ASPNETCORE_URLS=http://+:80

