version: '3.8'

services:
  my_dotnet_app:
    image: my_dotnet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80

