version: '3.8'

services:
  app:    
    environment:
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: ${{ secrets.DOCKER_USERNAME }}/my-app
    container_name: my_dotnet_app
    ports:
      - "5010:80"
 

