version: '3.8'

services:
  my_dotnet_app:
    image: adm1n1strati0n2/my-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5010:80"
    environment:
      - ASPNETCORE_URLS=http://+:80

